### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Gyshie**
Documentation - did some grammar and spelling changes.

### CODE REVIEW

**Review by AndrGab — APPROVED** [review]
thanks for your help

**Comment by AndrGab** [comment]
@Gyshie could yopu do the same with this repo?
https://github.com/AndrGab/medirepoWeb

**Comment by Gyshie** [comment]
Sure :)

**Comment by Gyshie** [comment]
Hi Andre, thanks for accepting my contribution.
Sure :) I will check the English documentation part of that repo as well.

**Pull request merged**
